<a href="https://colab.research.google.com/github/sidchaubey/Python_Revision/blob/master/All_In_One.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#  print("Hello")

In [2]:
import seaborn as sns

In [4]:
import tensorflow as tf

In [5]:
tf.__version__

'2.6.0'

In [6]:
%tensorflow_version 2.x

In [9]:
%%sh

pip install jupyter
pip install lxml
pip install matplotlib
pip install pandas
pip install Pillow
pip install scikit-learn
pip install seaborn
pip install tensorflow


pip freeze > requirements.txt

In [16]:
path = "/content/requirements.txt"

with open(path) as f:
  data = f.readlines()


print(data)

data_without_n = []

for i in data:
  data_without_n.append(i.split("==")[0])

print(data_without_n)

['absl-py==0.12.0\n', 'alabaster==0.7.12\n', 'albumentations==0.1.12\n', 'altair==4.1.0\n', 'appdirs==1.4.4\n', 'argcomplete==1.12.3\n', 'argon2-cffi==21.1.0\n', 'arviz==0.11.2\n', 'astor==0.8.1\n', 'astropy==4.3.1\n', 'astunparse==1.6.3\n', 'atari-py==0.2.9\n', 'atomicwrites==1.4.0\n', 'attrs==21.2.0\n', 'audioread==2.1.9\n', 'autograd==1.3\n', 'Babel==2.9.1\n', 'backcall==0.2.0\n', 'beautifulsoup4==4.6.3\n', 'bleach==4.1.0\n', 'blis==0.4.1\n', 'bokeh==2.3.3\n', 'Bottleneck==1.3.2\n', 'branca==0.4.2\n', 'bs4==0.0.1\n', 'CacheControl==0.12.6\n', 'cached-property==1.5.2\n', 'cachetools==4.2.2\n', 'catalogue==1.0.0\n', 'certifi==2021.5.30\n', 'cffi==1.14.6\n', 'cftime==1.5.0\n', 'chardet==3.0.4\n', 'charset-normalizer==2.0.5\n', 'clang==5.0\n', 'click==7.1.2\n', 'cloudpickle==1.3.0\n', 'cmake==3.12.0\n', 'cmdstanpy==0.9.5\n', 'colorcet==2.0.6\n', 'colorlover==0.3.0\n', 'community==1.0.0b1\n', 'contextlib2==0.5.5\n', 'convertdate==2.3.2\n', 'coverage==3.7.1\n', 'coveralls==0.5\n', 'crcmod

In [17]:
print("The number of packages preinstalled in colab are: ", len(data))

The number of packages preinstalled in colab are:  384


In [20]:
print('pandas' in data_without_n)
print("numpy" in data_without_n)

True
True


# Numpy

In [23]:
import numpy as np

lst = list(range(100))

print("Type of List: ", type(lst))
num_array = np.array(lst)
print(num_array)
print("Type of numpy array: ",type(num_array))

Type of List:  <class 'list'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Type of numpy array:  <class 'numpy.ndarray'>


In [24]:
%%timeit

[i**2 for i in lst]

10000 loops, best of 5: 24.7 µs per loop


In [26]:
%%timeit

num_array**2

The slowest run took 31.17 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 908 ns per loop


In [27]:
# 2-D matrix

lst_2d = [[1,2,3], [4,5,6]]

num_array2d = np.array(lst_2d)
print(num_array2d)
print(num_array2d.ndim)
print(num_array2d.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [31]:
num_arange = np.arange(start=0,stop=100, step=2)
num_arange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [35]:
# Numpy array containing zeros

print(np.zeros(3))
print("\n\n")
print(np.zeros((4,4)))
print("\n\n")
print(np.zeros((4,4,4)))

[0. 0. 0.]



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [37]:
print(np.ones((1,4)))

[[1. 1. 1. 1.]]


In [39]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [40]:
# Random

np.random.rand(100)

array([0.09350082, 0.96221813, 0.14228896, 0.10213096, 0.82796047,
       0.67072653, 0.33099002, 0.96170447, 0.8396554 , 0.36144859,
       0.68437683, 0.22822517, 0.7563542 , 0.74311086, 0.77206335,
       0.21384808, 0.44307845, 0.54624669, 0.18472809, 0.61397214,
       0.2086608 , 0.53002909, 0.48739103, 0.04359501, 0.10178127,
       0.9219625 , 0.13525815, 0.47802411, 0.88804619, 0.23158344,
       0.35337488, 0.67271782, 0.32537259, 0.57866089, 0.55614272,
       0.36100395, 0.42473838, 0.73426612, 0.66626626, 0.19977216,
       0.0802183 , 0.81863084, 0.22556851, 0.62541337, 0.61558855,
       0.87051603, 0.52152611, 0.242935  , 0.51205268, 0.14078287,
       0.18710753, 0.3995985 , 0.168682  , 0.08448166, 0.30840509,
       0.70398085, 0.32507747, 0.77015783, 0.77029232, 0.48197848,
       0.2444908 , 0.32838958, 0.37796489, 0.74793173, 0.44704187,
       0.31181512, 0.06550329, 0.59616569, 0.34227694, 0.42526755,
       0.42210175, 0.97437436, 0.91116036, 0.3265563 , 0.56766

In [41]:
np.random.rand(100)

array([0.8555444 , 0.42554401, 0.69043068, 0.22863864, 0.99380076,
       0.67469027, 0.89421389, 0.35039517, 0.89334209, 0.41895304,
       0.61217392, 0.514194  , 0.41904843, 0.8420032 , 0.6932197 ,
       0.19874263, 0.17636084, 0.46816496, 0.00189431, 0.95241545,
       0.9727813 , 0.27145776, 0.38429186, 0.3754964 , 0.36244689,
       0.48899164, 0.95654665, 0.23531976, 0.72314439, 0.92305138,
       0.84749482, 0.41790375, 0.47106497, 0.1924532 , 0.16514342,
       0.48382496, 0.47304099, 0.98476894, 0.5113662 , 0.19970573,
       0.17318296, 0.46396656, 0.12667752, 0.7002859 , 0.35001611,
       0.72303199, 0.78480878, 0.56937176, 0.65953012, 0.66325564,
       0.25666411, 0.96396571, 0.24449374, 0.32373977, 0.0306233 ,
       0.55979323, 0.80206018, 0.5477916 , 0.9865828 , 0.46015517,
       0.64524314, 0.84974704, 0.83896768, 0.86649559, 0.36239633,
       0.56307446, 0.28500024, 0.50469862, 0.41333345, 0.42591611,
       0.72426838, 0.5020566 , 0.30652968, 0.68286755, 0.86669

In [46]:
np.random.seed(0)

print(np.random.rand(10))


[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]


In [45]:
np.random.seed(0)

print(np.random.rand(10))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]


In [44]:
print(np.random.randn(10))
print(np.random.randn(10))

[ 1.49407907 -0.20515826  0.3130677  -0.85409574 -2.55298982  0.6536186
  0.8644362  -0.74216502  2.26975462 -1.45436567]
[ 0.04575852 -0.18718385  1.53277921  1.46935877  0.15494743  0.37816252
 -0.88778575 -1.98079647 -0.34791215  0.15634897]


In [48]:
np.random.randint(0, 100, 100)

array([79, 47, 64, 82, 99, 88, 49, 29, 19, 19, 14, 39, 32, 65,  9, 57, 32,
       31, 74, 23, 35, 75, 55, 28, 34,  0,  0, 36, 53,  5, 38, 17, 79,  4,
       42, 58, 31,  1, 65, 41, 57, 35, 11, 46, 82, 91,  0, 14, 99, 53, 12,
       42, 84, 75, 68,  6, 68, 47,  3, 76, 52, 78, 15, 20, 99, 58, 23, 79,
       13, 85, 48, 49, 69, 41, 35, 64, 95, 69, 94,  0, 50, 36, 34, 48, 93,
        3, 98, 42, 77, 21, 73,  0, 10, 43, 58, 23, 59,  2, 98, 62])

In [49]:
a = np.random.randint(0, 100, 100)
a.shape

(100,)

In [50]:
a.reshape(10,10)

array([[35, 94, 67, 82, 46, 99, 20, 81, 50, 27],
       [14, 41, 58, 65, 36, 10, 86, 43, 11,  2],
       [51, 80, 32, 54,  0, 38, 19, 46, 42, 56],
       [60, 77, 30, 24,  2,  3, 94, 98, 13, 40],
       [72, 19, 95, 72, 26, 66, 52, 67, 61, 14],
       [96,  4, 67, 11, 86, 77, 75, 56, 16, 24],
       [29, 21, 25, 80, 60, 61, 83, 33, 32, 70],
       [85, 31, 13, 71, 56, 24, 79, 41, 18, 40],
       [54, 79, 11, 38, 93,  1, 95, 44, 88, 24],
       [67, 82,  3, 76, 35, 86, 61, 69, 87, 43]])

In [52]:
a.reshape(10,5,2)

array([[[35, 94],
        [67, 82],
        [46, 99],
        [20, 81],
        [50, 27]],

       [[14, 41],
        [58, 65],
        [36, 10],
        [86, 43],
        [11,  2]],

       [[51, 80],
        [32, 54],
        [ 0, 38],
        [19, 46],
        [42, 56]],

       [[60, 77],
        [30, 24],
        [ 2,  3],
        [94, 98],
        [13, 40]],

       [[72, 19],
        [95, 72],
        [26, 66],
        [52, 67],
        [61, 14]],

       [[96,  4],
        [67, 11],
        [86, 77],
        [75, 56],
        [16, 24]],

       [[29, 21],
        [25, 80],
        [60, 61],
        [83, 33],
        [32, 70]],

       [[85, 31],
        [13, 71],
        [56, 24],
        [79, 41],
        [18, 40]],

       [[54, 79],
        [11, 38],
        [93,  1],
        [95, 44],
        [88, 24]],

       [[67, 82],
        [ 3, 76],
        [35, 86],
        [61, 69],
        [87, 43]]])

In [53]:
a.min()

0

In [54]:
a.max()

99

In [55]:
a.argmin()

24

In [56]:
a.argmax()

5

In [58]:
a[a.argmin()]

0

In [59]:
a[a.argmax()]

99

In [60]:
# indexing

print(a[0])
print(a[-1])
print(a[len(a)-1])
print(a[:10])
print(a[::-1])
print(a[::])

35
43
43
[35 94 67 82 46 99 20 81 50 27]
[43 87 69 61 86 35 76  3 82 67 24 88 44 95  1 93 38 11 79 54 40 18 41 79
 24 56 71 13 31 85 70 32 33 83 61 60 80 25 21 29 24 16 56 75 77 86 11 67
  4 96 14 61 67 52 66 26 72 95 19 72 40 13 98 94  3  2 24 30 77 60 56 42
 46 19 38  0 54 32 80 51  2 11 43 86 10 36 65 58 41 14 27 50 81 20 99 46
 82 67 94 35]
[35 94 67 82 46 99 20 81 50 27 14 41 58 65 36 10 86 43 11  2 51 80 32 54
  0 38 19 46 42 56 60 77 30 24  2  3 94 98 13 40 72 19 95 72 26 66 52 67
 61 14 96  4 67 11 86 77 75 56 16 24 29 21 25 80 60 61 83 33 32 70 85 31
 13 71 56 24 79 41 18 40 54 79 11 38 93  1 95 44 88 24 67 82  3 76 35 86
 61 69 87 43]


In [65]:
# Broadcasting

a = np.arange(10)
b = np.arange(10).reshape(-1, 1)

print(a.shape)
print(b.shape)

c = a+b
print(c)

(10,)
(10, 1)
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [69]:
c>10

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False,  True,
         True],
       [False, False, False, False, False, False, False,  True,  True,
         True],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [70]:
c[c>10]

array([11, 11, 12, 11, 12, 13, 11, 12, 13, 14, 11, 12, 13, 14, 15, 11, 12,
       13, 14, 15, 16, 11, 12, 13, 14, 15, 16, 17, 11, 12, 13, 14, 15, 16,
       17, 18])

In [72]:
# Numpy Operations

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [73]:
np.tanh(a)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997])

In [74]:
a-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [75]:
a-b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-2, -1,  0,  1,  2,  3,  4,  5,  6,  7],
       [-3, -2, -1,  0,  1,  2,  3,  4,  5,  6],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-6, -5, -4, -3, -2, -1,  0,  1,  2,  3],
       [-7, -6, -5, -4, -3, -2, -1,  0,  1,  2],
       [-8, -7, -6, -5, -4, -3, -2, -1,  0,  1],
       [-9, -8, -7, -6, -5, -4, -3, -2, -1,  0]])

In [76]:
a*b

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [82]:
d = a/a
d

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [83]:
type(d[0])

numpy.float64

In [84]:
d[0]

nan

In [85]:
f = 1/a
f

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [86]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [87]:
np.square(a)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [89]:
print(a)

np.cumsum(a)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [90]:
a.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
np.count_nonzero(a)

9

In [93]:
a.var()

8.25

In [94]:
a.std(
)

2.8722813232690143

In [95]:
a.mean()

4.5

In [97]:
np.median(a)

4.5

In [101]:
from scipy.stats import mode

v = np.random.randint(0,10, 10000)
mode(v)

ModeResult(mode=array([9]), count=array([1042]))

In [107]:
from collections import Counter

print(Counter(v))

print(Counter(v)[9])

Counter({9: 1042, 8: 1041, 1: 1034, 5: 1022, 3: 1005, 6: 989, 7: 975, 2: 970, 0: 963, 4: 959})
1042


In [112]:
from collections import defaultdict

a = defaultdict(lambda x: [])
a

defaultdict(<function __main__.<lambda>>, {})

# Pandas

In [113]:
!wget https://www.bis.org/statistics/full_bis_lbs_diss_csv.zip

--2021-09-19 20:14:18--  https://www.bis.org/statistics/full_bis_lbs_diss_csv.zip
Resolving www.bis.org (www.bis.org)... 185.58.128.7
Connecting to www.bis.org (www.bis.org)|185.58.128.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘full_bis_lbs_diss_csv.zip’

full_bis_lbs_diss_c     [   <=>              ]  52.35M  9.45MB/s    in 7.2s    

2021-09-19 20:14:26 (7.23 MB/s) - ‘full_bis_lbs_diss_csv.zip’ saved [54894511]



In [114]:
!unzip /content/full_bis_lbs_diss_csv.zip

Archive:  /content/full_bis_lbs_diss_csv.zip
  inflating: WEBSTATS_LBS_D_PUB_DATAFLOW_csv_col.csv  


In [115]:
import pandas as pd

df = pd.read_csv("/content/WEBSTATS_LBS_D_PUB_DATAFLOW_csv_col.csv")
df.head()

FREQ  Frequency L_MEASURE  ...   2020-Q3  2020-Q4   2021-Q1
0    Q  Quarterly         F  ...   -28.299 -388.690  -347.531
1    Q  Quarterly         F  ... -2013.523 -212.637 -2089.863
2    Q  Quarterly         F  ...   -23.363   -0.001     0.016
3    Q  Quarterly         F  ...  -591.110  -38.659  -417.187
4    Q  Quarterly         F  ...    -3.461   -0.317    -4.694

[5 rows x 199 columns]

In [116]:
df.shape

(282863, 199)

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282863 entries, 0 to 282862
Columns: 199 entries, FREQ to 2021-Q1
dtypes: float64(174), object(25)
memory usage: 429.5+ MB


In [121]:
df.describe()

1977-Q4        1978-Q1  ...       2020-Q4       2021-Q1
count   11993.000000   24324.000000  ...  2.356060e+05  2.338180e+05
mean     4767.375135    2417.093270  ...  3.993199e+04  4.041286e+04
std     30649.186664   22026.271811  ...  9.266695e+05  9.167538e+05
min    -44673.000000  -42983.000000  ... -2.288355e+05 -3.086983e+05
25%        12.000000       0.954000  ... -1.000000e-03  0.000000e+00
50%        86.000000      15.150000  ...  1.968000e+00  2.000000e+00
75%       679.000000     184.000000  ...  1.682933e+02  1.750000e+02
max    846506.000000  870151.000000  ...  1.234148e+08  1.217076e+08

[8 rows x 174 columns]

In [122]:
df.columns

Index(['FREQ', 'Frequency', 'L_MEASURE', 'Measure', 'L_POSITION',
       'Balance sheet position', 'L_INSTR', 'Type of instruments', 'L_DENOM',
       'Currency denomination',
       ...
       '2018-Q4', '2019-Q1', '2019-Q2', '2019-Q3', '2019-Q4', '2020-Q1',
       '2020-Q2', '2020-Q3', '2020-Q4', '2021-Q1'],
      dtype='object', length=199)

In [134]:
null_count = pd.DataFrame(df.isna().sum())

In [145]:
import seaborn as sns
import plotly.express as px


fig = px.bar(x=null_count.values.ravel(), y=null_count.index.ravel());
fig.show()

In [150]:
null_count.columns = ["count"]
null_count

count
FREQ            0
Frequency       0
L_MEASURE       0
Measure         0
L_POSITION      0
...           ...
2020-Q1     48134
2020-Q2     48534
2020-Q3     48479
2020-Q4     47257
2021-Q1     49045

[199 rows x 1 columns]

In [165]:
print(len(null_count[null_count["count"]>0].index))
null_columns = null_count[null_count["count"]>0].index

175


In [166]:
df_null = df.loc[:, null_columns]

In [157]:
non_null_columns = null_count[null_count["count"]==0].index

In [160]:
df_non_null = df.loc[:, non_null_columns]
df_non_null.head()

FREQ  Frequency  ... Position type                   Time Period
0    Q  Quarterly  ...  Cross-border  Q:F:C:A:CHF:A:5J:A:5A:A:1C:N
1    Q  Quarterly  ...  Cross-border  Q:F:C:A:CHF:A:5J:A:5A:A:1N:N
2    Q  Quarterly  ...  Cross-border  Q:F:C:A:CHF:A:5J:A:5A:A:1W:N
3    Q  Quarterly  ...  Cross-border  Q:F:C:A:CHF:A:5J:A:5A:A:1Z:N
4    Q  Quarterly  ...  Cross-border  Q:F:C:A:CHF:A:5J:A:5A:A:2B:N

[5 rows x 24 columns]

In [161]:
df_non_null.dtypes

FREQ                                  object
Frequency                             object
L_MEASURE                             object
Measure                               object
L_POSITION                            object
Balance sheet position                object
L_INSTR                               object
Type of instruments                   object
L_DENOM                               object
Currency denomination                 object
L_CURR_TYPE                           object
Currency type of reporting country    object
L_PARENT_CTY                          object
Parent country                        object
L_REP_BANK_TYPE                       object
Type of reporting institutions        object
L_REP_CTY                             object
Reporting country                     object
L_CP_SECTOR                           object
Counterparty sector                   object
Counterparty country                  object
L_POS_TYPE                            object
Position t

In [171]:
dict_val = {}

for i in df_non_null.dtypes:
  if i not in dict_val:
    dict_val[i] = 1
  else:
    dict_val[i] +=1

print(dict_val)

{dtype('O'): 24}


* Conclusion: **None of the columns have number value are all non-null**

In [167]:
df_null.head()

L_CP_COUNTRY  1977-Q4  1978-Q1  ...   2020-Q3  2020-Q4   2021-Q1
0           1C      NaN   -1.725  ...   -28.299 -388.690  -347.531
1           1N      NaN  -72.318  ... -2013.523 -212.637 -2089.863
2           1W      NaN      NaN  ...   -23.363   -0.001     0.016
3           1Z      NaN    2.900  ...  -591.110  -38.659  -417.187
4           2B      NaN -186.138  ...    -3.461   -0.317    -4.694

[5 rows x 175 columns]

In [168]:
df_null.dtypes

L_CP_COUNTRY     object
1977-Q4         float64
1978-Q1         float64
1978-Q2         float64
1978-Q3         float64
                 ...   
2020-Q1         float64
2020-Q2         float64
2020-Q3         float64
2020-Q4         float64
2021-Q1         float64
Length: 175, dtype: object

In [170]:
dict_val = {}

for i in df_null.dtypes:
  if i not in dict_val:
    dict_val[i] = 1
  else:
    dict_val[i] +=1

print(dict_val)

{dtype('O'): 1, dtype('float64'): 174}


* Conclusion : **Mainly null values are for numeric data type**

> Indented block



In [172]:
df["L_CP_COUNTRY"].value_counts()

5J    21719
CN     1270
PA     1268
KY     1264
SG     1264
      ...  
DD      264
2S      250
2T      234
2U      222
2D       92
Name: L_CP_COUNTRY, Length: 245, dtype: int64

In [177]:
df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum()

1977-Q4
L_CP_COUNTRY           
1C              77255.0
1N            1071182.0
1W                 56.0
1Z               3457.0
2B              50060.0
...                 ...
YE               7717.0
YU              44921.0
ZA              76575.0
ZM               5541.0
ZW                831.0

[245 rows x 1 columns]

In [181]:
df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum().iloc[df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum().values.argmax()]

1977-Q4    29101573.0
Name: 5J, dtype: float64

In [191]:
df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum().iloc[df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum().values.argmax()].index
df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum().iloc[df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum().values.argmax()].values
# df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum().iloc[df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum().values.argmax()].name

array([29101573.])

In [182]:
df[["L_CP_COUNTRY", "1977-Q4"]].groupby("L_CP_COUNTRY").sum().max()

1977-Q4    29101573.0
dtype: float64

* Conclusion: *SJ has highest overall value for quarter four year 1977*

In [195]:
print(f"Quarter: {df[['L_CP_COUNTRY', '1977-Q4']].groupby('L_CP_COUNTRY').sum().iloc[df[['L_CP_COUNTRY', '1977-Q4']].groupby('L_CP_COUNTRY').sum().values.argmax()].index},\
Name: {df[['L_CP_COUNTRY', '1977-Q4']].groupby('L_CP_COUNTRY').sum().iloc[df[['L_CP_COUNTRY', '1977-Q4']].groupby('L_CP_COUNTRY').sum().values.argmax()].name}, \
Value: {df[['L_CP_COUNTRY', '1977-Q4']].groupby('L_CP_COUNTRY').sum().iloc[df[['L_CP_COUNTRY', '1977-Q4']].groupby('L_CP_COUNTRY').sum().values.argmax()].values[0]}")

Quarter: Index(['1977-Q4'], dtype='object'),Name: 5J, Value: 29101573.0


In [213]:
for i in null_columns[1:]:
    # print(df[["L_CP_COUNTRY", i]].groupby("L_CP_COUNTRY").sum().iloc[df[["L_CP_COUNTRY", i]].groupby("L_CP_COUNTRY").sum().values.argmax()])
    # print(df[["L_CP_COUNTRY", i]].groupby("L_CP_COUNTRY").sum().iloc[df[["L_CP_COUNTRY", i]].groupby("L_CP_COUNTRY").sum().values.argmax()])
    print(f"Quarter: {df[['L_CP_COUNTRY', i]].groupby('L_CP_COUNTRY').sum().iloc[df[['L_CP_COUNTRY', i]].groupby('L_CP_COUNTRY').sum().values.argmax()].index[0]}, \
  Name: {df[['L_CP_COUNTRY', i]].groupby('L_CP_COUNTRY').sum().iloc[df[['L_CP_COUNTRY', i]].groupby('L_CP_COUNTRY').sum().values.argmax()].name}, \
  Value: {df[['L_CP_COUNTRY', i]].groupby('L_CP_COUNTRY').sum().iloc[df[['L_CP_COUNTRY', i]].groupby('L_CP_COUNTRY').sum().values.argmax()].values[0]}")

Quarter: 1977-Q4,   Name: 5J,   Value: 29101573.0
Quarter: 1978-Q1,   Name: 5J,   Value: 30301061.323
Quarter: 1978-Q2,   Name: 5J,   Value: 31835785.667999998
Quarter: 1978-Q3,   Name: 5J,   Value: 35605926.980000004
Quarter: 1978-Q4,   Name: 5J,   Value: 40498808.525
Quarter: 1979-Q1,   Name: 5J,   Value: 37646804.922
Quarter: 1979-Q2,   Name: 5J,   Value: 42667686.774000004
Quarter: 1979-Q3,   Name: 5J,   Value: 47789333.39
Quarter: 1979-Q4,   Name: 5J,   Value: 50681582.999
Quarter: 1980-Q1,   Name: 5J,   Value: 51458288.636
Quarter: 1980-Q2,   Name: 5J,   Value: 54319161.543
Quarter: 1980-Q3,   Name: 5J,   Value: 56407413.382
Quarter: 1980-Q4,   Name: 5J,   Value: 61907426.186000004
Quarter: 1981-Q1,   Name: 5J,   Value: 61749650.191
Quarter: 1981-Q2,   Name: 5J,   Value: 60721474.508
Quarter: 1981-Q3,   Name: 5J,   Value: 66077840.45
Quarter: 1981-Q4,   Name: 5J,   Value: 70805192.373
Quarter: 1982-Q1,   Name: 5J,   Value: 72000682.809
Quarter: 1982-Q2,   Name: 5J,   Value: 68241

In [204]:
categorical_columns = list(df_non_null.columns)
categorical_columns.append(list(df_null.columns)[0])
print(categorical_columns)

['FREQ', 'Frequency', 'L_MEASURE', 'Measure', 'L_POSITION', 'Balance sheet position', 'L_INSTR', 'Type of instruments', 'L_DENOM', 'Currency denomination', 'L_CURR_TYPE', 'Currency type of reporting country', 'L_PARENT_CTY', 'Parent country', 'L_REP_BANK_TYPE', 'Type of reporting institutions', 'L_REP_CTY', 'Reporting country', 'L_CP_SECTOR', 'Counterparty sector', 'Counterparty country', 'L_POS_TYPE', 'Position type', 'Time Period', 'L_CP_COUNTRY']


In [214]:

# for j in categorical_columns:
#   for i in null_columns[1:]:
#     print(f"Quarter: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmax()].index[0]}, \
#   Name: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmax()].name}, \
#   Value: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmax()].values[0]}")

In [215]:

# for j in categorical_columns:
#   for i in null_columns[1:]:
#     print(f"Categorical Column: {j}\
#     ,Numeric Column: {i}, \
#     Quarter: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmax()].index[0]}, \
#   Name: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmax()].name}, \
#   Value: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmax()].values[0]:.2f}")

In [233]:
with open("minvalue.txt", "w") as f:
  pass

with open("minvalue.txt", "a") as f:
  for j in categorical_columns[0:5]: # Iterating through just five categorical column as it takes quite a lot of time to run cell
    for i in null_columns[1:]:
      f.writelines(f"Categorical Column: {j}\
      ,Numeric Column: {i}, \
      Quarter: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmin()].index[0]}, \
    Name: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmin()].name}, \
    Value: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmin()].values[0]:.2f}\n")

In [234]:
with open("maxvalue.txt", "w") as f:
  pass

with open("maxvalue.txt", "a") as f:
  for j in categorical_columns[0:5]: # Iterating through just five categorical column as it takes quite a lot of time to run cell
    for i in null_columns[1:]:
      f.writelines(f"Categorical Column: {j}\
      ,Numeric Column: {i}, \
      Quarter: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmax()].index[0]}, \
    Name: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmax()].name}, \
    Value: {df[[j, i]].groupby(j).sum().iloc[df[[j, i]].groupby(j).sum().values.argmax()].values[0]:.2f}\n")

In [235]:
df["L_POSITION"].value_counts()

L    144708
C    138155
Name: L_POSITION, dtype: int64